name: sciolism_app
description: E - Learning application to support learning courses, taking quizzes,...

publish_to: 'none' 
version: 1.0.0+1

environment:
  sdk: ">=2.15.1 <3.0.0"


dependencies:
  flutter:
    sdk: flutter

  step_progress_indicator: ^1.0.2
  cupertino_icons: ^1.0.2
  firebase_storage: ^10.2.9
  firebase_core: ^1.13.1
  syncfusion_flutter_pdfviewer: ^19.4.56-beta
  json_annotation: ^4.4.0
  http: ^0.13.4
  video_player: ^2.3.0
  shared_preferences: ^2.0.15
  iconsax: ^0.0.8
  flutter_svg: ^1.0.3
  cloud_firestore: ^3.1.17
  cloud_functions: ^3.2.16
  firebase_messaging: ^11.4.1
  firebase_database: ^9.0.15
  firebase_auth: ^3.3.19
  email_auth: ^1.0.0
  cached_network_image: ^3.2.0
  charts_flutter: ^0.12.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  build_runner: ^2.1.8
  json_serializable: ^6.1.5

  # flutter_lints: ^1.0.0
  flutter_native_splash: ^2.1.6

flutter_native_splash:
  color: "#ffffff"
  image: assets/images/splash/splash.png

flutter:

  uses-material-design: true
  assets:
    - assets/json/
    - assets/images/splash/
    - assets/images/onboarding/
    - assets/images/authentication/

  fonts:
    - family: MsMadi
      fonts:
        - asset: assets/fonts/MsMadi-Regular.ttf
          style: normal
          weight: 400

    - family: Roboto
      fonts:
        - asset: assets/fonts/Roboto-Thin.ttf
          style: normal
          weight: 100
        - asset: assets/fonts/Roboto-ThinItalic.ttf
          style: italic
          weight: 100
        - asset: assets/fonts/Roboto-Light.ttf
          style: normal
          weight: 300
        - asset: assets/fonts/Roboto-LightItalic.ttf
          style: italic
          weight: 300
        - asset: assets/fonts/Roboto-Regular.ttf
          style: normal
          weight: 400
        - asset: assets/fonts/Roboto-Italic.ttf
          style: italic
          weight: 400
        - asset: assets/fonts/Roboto-Medium.ttf
          style: normal
          weight: 500
        - asset: assets/fonts/Roboto-MediumItalic.ttf
          style: italic
          weight: 500
        - asset: assets/fonts/Roboto-Bold.ttf
          style: normal
          weight: 700
        - asset: assets/fonts/Roboto-BoldItalic.ttf
          style: italic
          weight: 700
        - asset: assets/fonts/Roboto-Black.ttf
          style: normal
          weight: 900
        - asset: assets/fonts/Roboto-BlackItalic.ttf
          style: italic
          weight: 900